apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: spec-test-environment-location
  description: Location to import all spec-test-environment catalog components
spec:
  targets:
    - ./.platform/*.yaml
